name: Deploy tinyurl resources
on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy-infra:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout code
        uses: actions/checkout@main

      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy the infrastructure
        id: deploy-infra-resources
        uses: azure/arm-deploy@v2
        with:
          scope: "resourcegroup"
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          resourceGroupName: ${{ secrets.AZURE_RESOURCE_GROUP }}
          template: ./infra/main.bicep
          failOnStdErr: false
    outputs:
      functionAppName: ${{ steps.deploy-infra-resources.outputs.functionAppName }}

  deploy-code:
    needs: [deploy-infra]
    uses: ./.github/workflows/deploycode.yaml
    secrets: inherit
