on:
  workflow_call:

env:
  APP_LOCATION: "/" # location of your client code
  API_LOCATION: "api" # location of your api source code - optional
  OUTPUT_LOCATION: "dist" # location of client code build output

jobs:
  deploycode_reusable:
    defaults:
      run:
        shell: bash
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout code
        uses: actions/checkout@main

      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: get static web app token
        id: get-swa-token
        run: |
          appName=$(az staticwebapp list -g ${{ secrets.AZURE_RESOURCE_GROUP }} --query "[0].name" -o tsv)
          deployToken=$(az staticwebapp secrets list --name $appName --query "properties.apiKey" -o tsv)
          echo "echo "deploytoken=$deployToken" >> $GITHUB_OUTPUT"

      - name: Build And Deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ steps.get-swa-token.outputs.deployToken }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: ${{ env.APP_LOCATION }}
          api_location: ${{ env.API_LOCATION }}
          output_location: ${{ env.OUTPUT_LOCATION }}
        env:
          VITE_APP_CLIENT_ID: 6001765b-94fc-4e17-a55a-b8b66acc393a
          VITE_APP_AUTHORITY: https://login.microsoftonline.com/7175f825-a26f-4407-ae38-2dadd32dd3f9
