name: Deploy code
on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy-frontend:
    uses: ./.github/workflows/deploycode.yaml
    secrets: inherit
