name: Deploy frontend only
on:
  push:
    branches:
      - main
    paths:
      - "frontend/**"
      - ".github/workflows/deployweb.yaml"
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy-frontend:
    uses: ./.github/workflows/deploycode.yaml
    secrets: inherit
