name: Generate routes

permissions:
  contents: write
  actions: write

on:
  workflow_dispatch:

jobs:
  generate-routes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Generate Static HTML files
        run: |
          chmod +x ./util/generateroutes.sh
          ./util/generateroutes.sh ${{ secrets.GITHUB_TOKEN }}
        shell: bash
