name: Generate static HTML

on:
  push:
    branches:
      - main
    paths:
      - "urls.json"
  workflow_dispatch:

jobs:
  generate-html:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Generate Static HTML files
        run: |
          chmod +x ./util/generatehtml.sh
          ./util/generate-html.sh ${{ secrets.GITHUB_TOKEN }}
        shell: bash
